### ISSUE TITLE
Can't Extract File

### ISSUE THREAD

**Issue by ghost** [micooz/pixelart#1]
Output:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sptm.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp41isom
    creation_time   : 2017-12-15T14:27:25.000000Z
  Duration: 00:00:24.83, start: 0.000000, bitrate: 1360 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p, 1008x566 [SAR 1:1 DAR 504:283], 1234 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2017-12-15T14:27:25.000000Z
      handler_name    : VideoHandler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2017-12-15T14:27:25.000000Z
      handler_name    : SoundHandler
[NULL @ 0x17e7bb0] Unable to find a suitable output format for './frames/%05d.png'
./frames/%05d.png: Invalid argument
/home/pi/pixelart/scripts/img2text.js:11
function imageToAscii({data, width, height, contrast, channels = 3}) {
                      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
rm: 无法删除'./frames/*.png': 没有那个文件或目录

**Comment by micooz** [comment]
Please upgrade your Node.js to the latest stable version and try again.
